package com.hjx.v2ex.server.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseUserreply<M extends BaseUserreply<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public M setContact(java.lang.String contact) {
		set("contact", contact);
		return (M)this;
	}

	public java.lang.String getContact() {
		return get("contact");
	}

	public M setReply(java.lang.String reply) {
		set("reply", reply);
		return (M)this;
	}

	public java.lang.String getReply() {
		return get("reply");
	}

	public M setAppversion(java.lang.String appversion) {
		set("appversion", appversion);
		return (M)this;
	}

	public java.lang.String getAppversion() {
		return get("appversion");
	}

}
