package com.hjx.v2ex.server.common.model;

import com.hjx.v2ex.server.common.model.base.BaseUserreply;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Userreply extends BaseUserreply<Userreply> {
	public static final Userreply dao = new Userreply().dao();
}
